name: Removal Request (下架请求)
description: Content owner asks to remove an item.
labels: ["removal-request"]
body:
  - type: input
    id: item_url
    attributes:
      label: Item URL (条目链接)
      placeholder: https://...
    validations:
      required: true
  - type: textarea
    id: reason
    attributes:
      label: Reason / Proof
      description: Please provide proof of ownership if possible.
    validations:
      required: true
