name: Submit a Case (提交案例)
description: Submit a Seedance 2.0 case with full prompt, credits, and optional preview media.
labels: ["case"]
body:
  - type: input
    id: title
    attributes:
      label: Title
    validations:
      required: true

  - type: input
    id: url
    attributes:
      label: Source URL (原链接)
      description: The original post/video/article link.
      placeholder: https://...
    validations:
      required: true

  - type: input
    id: author
    attributes:
      label: Author / Handle (作者)
      description: If unknown, write "Unknown" (will be marked needs-credit).
      placeholder: @handle / name / Unknown
    validations:
      required: true

  - type: textarea
    id: summary
    attributes:
      label: Summary (一句话摘要)
      placeholder: Why this case is awesome.
    validations:
      required: true

  - type: textarea
    id: tags
    attributes:
      label: Tags (comma-separated)
      placeholder: multi-shot, audio, chase, tracking-shot
    validations:
      required: true

  - type: textarea
    id: prompt
    attributes:
      label: Full Prompt (全文提示词，可选)
      description: Paste the full prompt if you can.
      render: text
    validations:
      required: false

  - type: dropdown
    id: preview_kind
    attributes:
      label: Preview Media Kind (预览类型)
      description: Optional. If provided, it may be embedded in the gallery.
      options:
        - none
        - image
        - gif
        - video
    validations:
      required: true

  - type: input
    id: preview_url
    attributes:
      label: Preview Media URL (预览链接)
      description: Optional. A thumbnail/image/GIF/video URL that is safe to embed.
      placeholder: https://...
    validations:
      required: false

  - type: checkboxes
    id: preview_rights
    attributes:
      label: Preview Permission (预览授权)
      description: Required if you provide Preview Media URL. Tick ONE that applies.
      options:
        - label: I am the author / I have explicit permission from the author to embed this preview.
          required: false
        - label: This preview is a platform-provided thumbnail (e.g., YouTube thumbnail) and embedding is allowed by the platform.
          required: false

  - type: input
    id: metrics
    attributes:
      label: Metrics (热度，可选)
      description: e.g. upvotes/comments/views/stars.
      placeholder: upvotes=439, comments=57
    validations:
      required: false
